executors:
  default:
    working_directory: /root
    environment:
      FOO: bar
    docker:
      - image: buildpack-deps:buster@sha256:c343da4a0b85a4d25ce30529e836a10d46cd4f682fb5326400e4ba274a2f9866
  db:
    parameters:
      image_tag:
        type: string
      image_sha:
        type: string
        # default: buster@sha256:c343da4a0b85a4d25ce30529e836a10d46cd4f682fb5326400e4ba274a2f9866
    working_directory: /root
    environment:
      FOO: bar
    docker:
      - image: buildpack-deps:<< parameters.image_tag >>@<< parameters.image_sha >>
      - image: postgres:11.4-alpine@sha256:4e1c3bc6bc803d239613375ad8b8525ef8e9bce43ff4d97d1ad21a9ac0251396
