steps:
  - command: cat docker-compose.yml
    plugins:
      - ./.buildkite/plugins/autogen-docker-compose:
          input_path: .circleci/config.yml
          output_path: docker-compose.yml
          executor: db
    agents:
      queue: demo
